### ISSUE TITLE
multiple days version

### ISSUE THREAD

**Issue by simon2022** [tcellerier/Pico_ePaper_73#1]
Thank you very much for your effort and your improved version.

Would it be possible for you to upload prefabricated versions for a picture change in 2, 4, 7 days?
I would really appreciate it.

Thank you very much

**Comment by tcellerier** [comment]
Yes sure, will upload it today!

**Comment by tcellerier** [comment]
All 3 requested versions have been uploaded for Mode 3, which is the only mode I'm supporting today.

**Comment by I-III-I** [comment]
Maybe 7 days isn't a good idea. From the website:

When using the e-Paper display, it is recommended that the refresh interval be at least 180s, and refresh at least once every 24 hours. If the e-Paper is not used for a long time, you should use the program to clear the screen before storing it. (Refer to the datasheet for specific storage environment requirements.)

I also think "Maximum files increased to 2000 " will not work. You use:

#define fileNumber 2000
#define fileLen 100

    char temp[fileNumber][fileLen];
    char templist1[fileNumber/2][fileLen];
    char templist2[fileNumber/2][fileLen];

that are 400000 byte, but the RP2040 only has 264kB of embedded SRAM

At http://onlib.de/pub/PhotoPainter/ is a version for 90000 pictures, but they must 
have the fixed names: 10000.bmp, 10001.bmp, .... 99999.bmp 

There is also batch code for generating calendar pictures (a perfect usage for the PhotoPainter).

**Comment by tcellerier** [comment]
@I-III-I Your comment is surprising because I tested it with 2000 files before releasing it and it worked perfectly fine.
