### ISSUE TITLE
issues with pic loading

### ISSUE THREAD

**Issue by fsteckel** [tcellerier/Pico_ePaper_73#4]
Hi there!

I am using extra_uf2/Mode 3/rtc_1_hour.uf2 firmware. (others also show the same problem)
I seem to be having issues with the pic loading. I transfered the waveshare example images in the pic folder. A fileList.txt with the following content is being created (indicating, that the frame can read the card):
pic/0006.bmp.PFILE
pic/0008.bmp.PFILE
pic/0001.bmp.PFILE
pic/0007.bmp.PFILE
pic/0004.bmp.PFILE
pic/0002.bmp.PFILE
pic/0003.bmp.PFILE
pic/0009.bmp.PFILE
pic/0010.bmp.PFILE
pic/0005.bmp.PFILE
Also an index.txt with the content 1 is being created.

But with the card inserted and me pressing NEXT it will not update the frame but instead reboot after some seconds. When I leave the sd card out and push the NEXT button, it does update the frame and displays the example image (picture frames of flowers).
Any help is really appreciated.
Thanks,

Florian

**Comment by tcellerier** [comment]
From what I see, there is an issue with your image files, not the firmware.
The .pfile extension is not a standard format for image s I think this is where the issue is.
