### ISSUE TITLE
real randomizer

### ISSUE THREAD

**Issue by raffi099** [tcellerier/Pico_ePaper_73#5]
Thank you very much, thats almost what i was looking for!
I have noticed, that at the beginning, all pics on the SDCarde are randomly sorted. But after that, the sequence stays the same, right?
Is there a way that every time the pic changes, the pic is again, randomly choosed, so there is no such thing as a "sequence"?
I want to be every morning surprized which pic is on the PhotoPainter, without take the SDCard out and delete the "fileList.txt".

Sry for bad english. I hope my question/wish is understandable.

Im not really that good of a programer myself... but i think it should work if the "fileList.txt" is generated again after every changeing of the display? Is there any chance you could modify the firmware again? That would be so cool.

**Comment by tcellerier** [comment]
Currently, the file order is indeed random, but it is determined by a seed based on the number of files. This means that the "random" order will remain consistent as long as the number of files stays the same. Therefore, if you remove fileList.txt without changing the number of pictures, the order will remain unchanged. With the current firmware, the only way to change the order is by changing the number of files.
Unfortunately, the behavior you're describing isn't possible with the current firmware and would require further development. Additionally, implementing this feature might affect battery life negatively.

**Comment by I-III-I** [comment]
Just a note:
On the 32 Gbyte SD card  you can store about 28k pictures.
If you display 2 every day, this is enough for 38 years.
If you have 1000 pictures, copy them in a random order
(you can even use real random numbers from random.org)
onto the SD card again and again until the card is full
and then display the pictures in sequence. This has
also the advantage, that you can add the date to the
pictures and have a calendar with true random pictures.

Take a look at: https://www.onlib.de/pub/PhotoPainter/


Here two sample pictures:

https://www.onlib.de/pub/PhotoPainter/10005.jpg
https://www.onlib.de/pub/PhotoPainter/10005.png
https://www.onlib.de/pub/PhotoPainter/10548.jpg
https://www.onlib.de/pub/PhotoPainter/10548.png
